version: '3.8'
services:
  php:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=hr441
      - DB_USER=root
      - DB_PASS=secret
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hr441
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
  analytics:
    build: ./python
    command: uvicorn services.analytics_api:app --host 0.0.0.0 --port 8001
    ports:
      - '8001:8001'

volumes:
  db_data:
